### PR TITLE
chore soc-854 Update comments boundary character in gem

### PR DESCRIPTION
**Pull request by Hedi84**
Updating the gem to match the new boundary character for mentioning

https://fuseuniversal.atlassian.net/browse/SOC-854

image

## Related PR:

https://github.com/Fuseit/FuseTube/pull/7138

### CODE REVIEW

**Review by korki — APPROVED** [review]
please update the readme as well!

**Review by Wil0 — APPROVED** [review]
LGTM, just double checking if  we need to update the version of the gem because of this change, as we spoke offline yesterday?

**Comment by filipebarros** [comment]
@Hedi84 fuse-dev-tools has a release script that you can use to create a release. It hasn't been tested with other apps but it should work fine. Using that we can cut a new release and then use the release version in the `Gemfile`

**Comment by Hedi84** [comment]
@filipebarros that sounds good, thank you! Hopefully you have some time on Monday to give me a hand with that?

**Pull request merged**
